version: '3.8'

services:
  deep-research-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deep-research-agent
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - DEBUG=${DEBUG:-False}
      - API_VERSION=${API_VERSION:-v1}
    networks:
      - deep-research-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  deep-research-network:
    driver: bridge
